"""
Utility to mirror key Phase 2 documentation into the formal reports directory.

The roadmap originally called for PDF deliverables; for now we generate Markdown
copies under ``playground/reports/phase2`` so downstream tooling has a single
collection point. Run this script whenever the source docs change.
"""

from __future__ import annotations

from datetime import UTC
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = PROJECT_ROOT / "playground" / "docs"
REPORTS_DIR = PROJECT_ROOT / "playground" / "reports" / "phase2"

# (source filename, destination filename)
REPORT_SOURCES: list[tuple[str, str]] = [
    ("factor_methodology.md", "factor_methodology.md"),
    ("regression_diagnostics.md", "regression_diagnostics.md"),
    ("factor_correlation_analysis.md", "factor_correlation_analysis.md"),
    ("pca_sector_returns.md", "pca_sector_returns.md"),
    ("rolling_beta_analysis.md", "rolling_beta_analysis.md"),
    ("beta_comparison_report.md", "beta_comparison_report.md"),
    ("beta_stability_justification.md", "beta_stability_justification.md"),
    ("chow_test_results.md", "chow_test_results.md"),
    ("phase_2_executive_summary.md", "phase_2_executive_summary.md"),
]


def export_reports() -> None:
    """Copy curated documentation into the reports directory."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now(tz=UTC).isoformat()

    for source_name, dest_name in REPORT_SOURCES:
        source_path = DOCS_DIR / source_name
        if not source_path.exists():
            msg = f"Source document missing: {source_path}"
            raise FileNotFoundError(msg)

        destination_path = REPORTS_DIR / dest_name
        content = source_path.read_text(encoding="utf-8")

        header = (
            "<!--\n"
            f"Generated from playground/docs/{source_name} on {timestamp}.\n"
            "Do not edit this file directly; update the source document instead.\n"
            "-->\n\n"
        )
        destination_path.write_text(header + content, encoding="utf-8")


if __name__ == "__main__":
    export_reports()
