"""
Utility to publish Phase 3 monitoring integration payloads.

This script reads the consolidated monitoring snapshot generated by
``export_phase3_monitoring_snapshot`` and persists Grafana/PagerDuty payloads
along with a manifest summarising the artefact locations. Optional dry-run
support emits a PagerDuty rehearsal file that can be used to walk through alert
escalation scenarios without touching live services.

"""

from __future__ import annotations

import argparse
import json
from collections.abc import Mapping
from datetime import UTC
from datetime import datetime
from pathlib import Path
from typing import Any

import structlog

from playground.backtest.runner import MonitoringSnapshotResult
from playground.monitoring.integrations import build_grafana_payload
from playground.monitoring.integrations import build_pagerduty_payload
from playground.monitoring.integrations import persist_monitoring_integrations


LOGGER = structlog.get_logger(__name__)
DEFAULT_SNAPSHOT_PATH = Path("playground/reports/backtesting/phase3_monitoring_snapshot.json")
DEFAULT_OUTPUT_DIR = Path("playground/reports/backtesting")
DEFAULT_MANIFEST_NAME = "monitoring/automation_manifest.json"
DEFAULT_ESCALATION_FILENAME = "monitoring/pagerduty_escalation_dry_run.json"


def _load_snapshot(path: Path) -> MonitoringSnapshotResult:
    if not path.exists():
        raise FileNotFoundError(f"Monitoring snapshot not found at {path}")
    payload = json.loads(path.read_text(encoding="utf-8"))
    return MonitoringSnapshotResult(path=path, payload=payload)


def _write_json(path: Path, payload: dict[str, Any]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    return path


def publish_phase3_monitoring_integrations(
    *,
    snapshot_path: Path,
    output_dir: Path,
    manifest_name: str = DEFAULT_MANIFEST_NAME,
    simulate_escalation: bool = False,
) -> dict[str, Path | None]:
    """
    Persist monitoring integration payloads and return output paths.
    """
    snapshot = _load_snapshot(snapshot_path)
    artefacts = persist_monitoring_integrations(snapshot=snapshot, output_dir=output_dir)

    grafana_payload = build_grafana_payload(snapshot.payload)
    pagerduty_payload = build_pagerduty_payload(snapshot.payload)
    sections = snapshot.payload.get("sections")
    benchmark_section: Mapping[str, Any] | None = None
    if isinstance(sections, Mapping):
        raw_benchmark = sections.get("benchmarks")
        if isinstance(raw_benchmark, Mapping):
            benchmark_section = raw_benchmark

    phase4_grafana = grafana_payload.get("phase4", {})
    manifest_payload = {
        "generated_at": datetime.now(tz=UTC).isoformat(),
        "snapshot_path": str(snapshot.path.resolve()),
        "grafana_payload_path": str(artefacts.grafana_payload_path.resolve()),
        "pagerduty_payload_path": str(artefacts.pagerduty_payload_path.resolve()),
        "grafana_dashboard_target": grafana_payload.get("dashboard_target"),
        "grafana_alert_rule": grafana_payload.get("alert_rule"),
        "pagerduty_service_rule": pagerduty_payload.get("service_rule"),
        "automation_targets": grafana_payload.get("automation_targets", {}),
        "phase4": {
            "sensitivity_summary_path": phase4_grafana.get("sensitivity", {}).get("summary_path"),
            "sensitivity_report_path": phase4_grafana.get("sensitivity", {}).get("report_path"),
            "data_quality_audit_path": phase4_grafana.get("data_quality", {}).get("audit_path"),
            "outlier_report_path": phase4_grafana.get("outliers", {}).get("report_path"),
        },
    }
    if benchmark_section is not None:
        manifest_payload["benchmarks"] = {
            "root": benchmark_section.get("root"),
            "latest_slug": benchmark_section.get("latest_slug"),
            "summary_path": benchmark_section.get("summary_path"),
            "baseline_metrics_path": benchmark_section.get("baseline_metrics_path"),
            "comparison_path": benchmark_section.get("comparison_path"),
            "audit_path": benchmark_section.get("audit_path"),
            "metadata_path": benchmark_section.get("metadata_path"),
        }
    manifest_path = _write_json(output_dir / manifest_name, manifest_payload)

    escalation_path: Path | None = None
    if simulate_escalation:
        phase4_pagerduty = pagerduty_payload.get("phase4", {})
        escalation_payload = {
            "generated_at": manifest_payload["generated_at"],
            "service_rule": pagerduty_payload.get("service_rule"),
            "proxy_dataset_status": pagerduty_payload.get("proxy_dataset_metadata", {}),
            "vintage_windows": pagerduty_payload.get("vintage_metadata", []),
            "diagnostics": pagerduty_payload.get("diagnostics_metadata", {}),
            "phase4": {
                "sensitivity_metadata": phase4_pagerduty.get("sensitivity", {}).get("metadata", []),
                "data_quality_summary": phase4_pagerduty.get("data_quality", {}).get("summary"),
                "outlier_summary": phase4_pagerduty.get("outliers", {}).get("summary"),
            },
        }
        if benchmark_section is not None:
            escalation_payload["benchmarks"] = {
                "summary_path": benchmark_section.get("summary_path"),
                "audit_path": benchmark_section.get("audit_path"),
                "latest_slug": benchmark_section.get("latest_slug"),
            }
        escalation_path = _write_json(output_dir / DEFAULT_ESCALATION_FILENAME, escalation_payload)

    LOGGER.info(
        "phase3_monitoring_integrations_published",
        manifest=str(manifest_path.resolve()),
        grafana_payload=str(artefacts.grafana_payload_path.resolve()),
        pagerduty_payload=str(artefacts.pagerduty_payload_path.resolve()),
        escalation=str(escalation_path.resolve()) if escalation_path else None,
    )

    return {
        "manifest": manifest_path,
        "grafana_payload": artefacts.grafana_payload_path,
        "pagerduty_payload": artefacts.pagerduty_payload_path,
        "escalation": escalation_path,
    }


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Publish Phase 3 monitoring integration payloads.")
    parser.add_argument(
        "--snapshot-path",
        type=Path,
        default=DEFAULT_SNAPSHOT_PATH,
        help="Path to the monitoring snapshot JSON (default: %(default)s)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory containing monitoring artefacts (default: %(default)s)",
    )
    parser.add_argument(
        "--manifest-name",
        type=str,
        default=DEFAULT_MANIFEST_NAME,
        help="Relative path for the automation manifest within the output directory.",
    )
    parser.add_argument(
        "--simulate-escalation",
        action="store_true",
        help="Emit a PagerDuty rehearsal payload to support escalation dry-runs.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    publish_phase3_monitoring_integrations(
        snapshot_path=args.snapshot_path,
        output_dir=args.output_dir,
        manifest_name=args.manifest_name,
        simulate_escalation=args.simulate_escalation,
    )


if __name__ == "__main__":
    main()
