-- Strategy signals and decisions schema for ML module
-- Stores trading signals, decisions, and strategy state

-- Switch to ML schema
SET search_path TO ml, public;

-- Strategy signals table
CREATE TABLE IF NOT EXISTS ml_strategy_signals (
    id BIGSERIAL PRIMARY KEY,
    strategy_id VARCHAR(64) NOT NULL,
    instrument_id VARCHAR(64) NOT NULL,
    signal_type VARCHAR(32) NOT NULL,  -- BUY, SELL, HOLD
    signal_strength FLOAT,              -- Signal confidence/strength
    model_predictions JSONB,            -- Predictions from various models
    risk_metrics JSONB,                 -- Risk calculations at decision time
    execution_params JSONB,             -- Position size, stop loss, etc.
    ts_event BIGINT NOT NULL,          -- Event timestamp (nanoseconds)
    ts_init BIGINT NOT NULL,           -- Initialization timestamp
    is_live BOOLEAN DEFAULT FALSE,     -- Whether from live trading or backtest
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for strategy signals
CREATE INDEX IF NOT EXISTS idx_ml_signals_strategy_instrument 
    ON ml_strategy_signals(strategy_id, instrument_id, ts_event DESC);
CREATE INDEX IF NOT EXISTS idx_ml_signals_time 
    ON ml_strategy_signals(ts_event DESC);
CREATE INDEX IF NOT EXISTS idx_ml_signals_type 
    ON ml_strategy_signals(signal_type);

-- Strategy metadata table
CREATE TABLE IF NOT EXISTS ml_strategy_metadata (
    strategy_id VARCHAR(64) PRIMARY KEY,
    strategy_type VARCHAR(64),
    configuration JSONB,        -- Strategy configuration parameters
    risk_parameters JSONB,      -- Stop loss, position sizing, etc.
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Strategy performance table
CREATE TABLE IF NOT EXISTS ml_strategy_performance (
    id BIGSERIAL PRIMARY KEY,
    strategy_id VARCHAR(64) NOT NULL,
    instrument_id VARCHAR(64),
    period_start TIMESTAMP WITH TIME ZONE NOT NULL,
    period_end TIMESTAMP WITH TIME ZONE NOT NULL,
    total_signals INTEGER DEFAULT 0,
    buy_signals INTEGER DEFAULT 0,
    sell_signals INTEGER DEFAULT 0,
    hold_signals INTEGER DEFAULT 0,
    total_trades INTEGER DEFAULT 0,
    winning_trades INTEGER DEFAULT 0,
    losing_trades INTEGER DEFAULT 0,
    total_pnl DECIMAL(20, 8),
    sharpe_ratio FLOAT,
    max_drawdown FLOAT,
    win_rate FLOAT,
    metadata JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (strategy_id) REFERENCES ml_strategy_metadata(strategy_id)
);

-- Strategy state table (for recovery)
CREATE TABLE IF NOT EXISTS ml_strategy_state (
    strategy_id VARCHAR(64) PRIMARY KEY,
    instrument_id VARCHAR(64) NOT NULL,
    current_position VARCHAR(32),  -- LONG, SHORT, FLAT
    position_size DECIMAL(20, 8),
    entry_price DECIMAL(20, 8),
    stop_loss_price DECIMAL(20, 8),
    take_profit_price DECIMAL(20, 8),
    signals_received INTEGER DEFAULT 0,
    trades_executed INTEGER DEFAULT 0,
    dry_run_trades INTEGER DEFAULT 0,
    state_data JSONB,  -- Additional state for recovery
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (strategy_id) REFERENCES ml_strategy_metadata(strategy_id)
);

-- Comments
COMMENT ON TABLE ml_strategy_signals IS 'All trading signals generated by ML strategies';
COMMENT ON TABLE ml_strategy_metadata IS 'Strategy configuration and metadata';
COMMENT ON TABLE ml_strategy_performance IS 'Strategy performance metrics over time';
COMMENT ON TABLE ml_strategy_state IS 'Current strategy state for recovery and monitoring';

-- Grant permissions
GRANT ALL ON ALL TABLES IN SCHEMA ml TO postgres;
GRANT ALL ON ALL SEQUENCES IN SCHEMA ml TO postgres;