# Override to use main nautilus-database
services:
  ml_pipeline:
    environment:
      DB_CONNECTION: postgresql://postgres:postgres@nautilus-database:5432/nautilus
    networks:
      - docker_nautilus-network
      - nautilus-ml

networks:
  docker_nautilus-network:
    external: true
